### ISSUE TITLE
About alpha

### ISSUE THREAD

**Issue by C0D3-M4513R** [adde0109/Ambassador#13]
Is there a particular reason, why this is still in active alpha?
Any particular shortcommings, or do you just need to cleanup code a little to feel sure?

If it helps, my server-network would like to run 1.13+ forge servers behind a proxy, without needing client-side mods. We would like to test out this plugin internally. 
Is there anything we should be aware of, in terms of user-sided unintentional behaviour, exploits, security etc?

**Comment by adde0109** [comment]
The main why it is still in alpha is because of stability. It is not guaranteed to work everytime with every setup and not completly bug free. What is lacking is correctly handling when they players mods missmatch and other errors that might occur. But other than there is also some configuration features that are missing right now that should be there, like custom kick messages and timeouts that are currently hard-coded when they shouldn't. I
